language: node_js
node_js:
  - "12"

addons:
  apt:
    packages:
    - exiv2
    - libexiv2-dev
    - cifs-utils
    - chromium-browser
    - libgconf-2-4

  chrome: stable


cache:
  npm: true
  directories:
  - ~/.cache

script:
  - npm run test-server
  - npm run test-client
  - npm run test-gui
