os: linux
dist: focal

language: node_js
node_js:
  - "14"

addons:
  apt:
    packages:
    - exiv2
    - libexiv2-dev
    - cifs-utils
    - chromium-browser
    - libgconf-2-4
    - xvfb

  chrome: stable

# cache:
#   npm: true
#   directories:
#   - ~/.cache

install:
  # https://electronjs.org/docs/tutorial/testing-on-headless-ci
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm ci

script:
  - make test
  - make lint
