addons:
  apt:
    packages:
    - exiv2
    - libexiv2-dev
    - cifs-utils
    - chromium-browser

  chrome: stable

language: node_js
node_js:
  - "12"

script:
  - npm run test-server
  - npm run test-client
  - npm run test-gui
