name: kiosk
base: core18
version: '1'
summary: A kiosk for your home
description: |
  A kiosk displaying all your local/samba pictures on a screen
grade: stable
confinement: strict

apps:
  kiosk:
    command: npm start
    plugs: 
      - network-bind
      - browser-sandbox
      - opengl


parts:
  kiosk:
    plugin: nodejs
    nodejs-version: "12.8.0"
    nodejs-package-manager: npm
    source: .
    build-packages:
      - python
      - build-essential
    stage-packages:
      - jq
      - exiv2 
      - libexiv2-dev
      - cifs-utils
      - chromium-browser
