#!/usr/bin/env bash

# https://github.com/hfuchs/usbmount
# https://github.com/rbrito/usbmount
# UM_DEVICE       - filename of the device node
# UM_MOUNTPOINT   - mointpoint
# UM_FILESYSTEM   - filesystem type
# UM_MOUNTOPTIONS - mount options that have been passed to the mount command
# UM_VENDOR       - vendor of the device (empty if unknown)
# UM_MODEL        - model name of the device (empty if unknown)

# echo "$(date) MOUNT $UM_MOUNTPOINT" >> /tmp/kiosk-usbmount.log
/opt/web/www/bin/kiosk-send-message.js \
	-o 'usbmount' \
	-t 'filesystem.mount' \
	-v "$UM_MOUNTPOINT" \
	-i "$UM_DEVICE"
