name: Makefile

on:
  push:
    branches:
    - main
    - ci/**
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  ga-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: dc dump
      uses: jehon/actions-devcontainer@main
      with:
        action: dump

    - id: start
      name: dc start
      uses: jehon/actions-devcontainer@main
      with:
        action: start

    - name: make dump
      uses: jehon/actions-devcontainer@main
      with:
        run: make dump

    - name: make build
      uses: jehon/actions-devcontainer@main
      with:
        run: make build

    - name: make test
      uses: jehon/actions-devcontainer@main
      with:
        run: make test

    - name: make lint
      uses: jehon/actions-devcontainer@main
      with:
        run: make lint

    - name: dc stop
      uses: jehon/actions-devcontainer@main
      if: always()
      with:
        action: stop
