
on:
  push:
    branches:
    - main
    - ci/**
  pull_request:
    branches:
    - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  ga-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: make dump
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: make dump

    - name: make build
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: make build

    - name: make lint
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: make lint

    - name: make test
      uses: devcontainers/ci@v0.3
      with:
        push: never
        runCmd: make test
