name: Makefile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ga-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: configure
      run: make configure

    - name: dump
      run: make dump

    - name: build
      run: make build

    - name: test
      run: make test
      
    - name: lint
      run: make lint
