name: Makefile

on:
  push:
    branches:
    - main
    - ci/**
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  ga-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Build docker images
      run: docker build -t local -f .devcontainer/Dockerfile .

    - name: make dump
      run: docker run -v $PWD:/workspace -w /workspace local make dump

    - run: make computer-setup
    - run: make dump
    - run: make build
    - run: make test
    - run: make lint
