name: Makefile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ga-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - run: make computer-setup
    - run: make dump
    - run: make build
    - run: make test
    - run: make lint
